services:
  _defaults:
    public: false
    autowire: true

  FreshAdvance\Invoice\Service\Invoice:
    class: FreshAdvance\Invoice\Service\Invoice
    public: true

  FreshAdvance\Invoice\Service\InvoiceServiceInterface:
    class: FreshAdvance\Invoice\Service\InvoiceService
    public: true

  FreshAdvance\Invoice\Service\OrderServiceInterface:
    class: FreshAdvance\Invoice\Service\OrderService
