services:
  _defaults:
    public: false
    autowire: true

  FreshAdvance\Invoice\Service\Invoice:
    class: FreshAdvance\Invoice\Service\Invoice
    public: true

  FreshAdvance\Invoice\Service\InvoiceServiceInterface:
    class: FreshAdvance\Invoice\Service\InvoiceService
    public: true

  NumberToWords\NumberToWords:
    class: NumberToWords\NumberToWords
    public: true

  FreshAdvance\Invoice\Service\NumberWordingServiceInterface:
    class: FreshAdvance\Invoice\Service\NumberWordingService
    public: true
