services:
  _defaults:
    public: false
    autowire: true

  FreshAdvance\Invoice\Service\RequestDataConverterInterface:
    class: FreshAdvance\Invoice\Service\RequestDataConverter
    public: true

  FreshAdvance\Invoice\Service\ContextInterface:
    class: FreshAdvance\Invoice\Service\Context
    public: true

  FreshAdvance\Invoice\Service\ModuleSettingsInterface:
    class: FreshAdvance\Invoice\Service\ModuleSettings
    public: true

  FreshAdvance\Invoice\Service\Invoice:
    class: FreshAdvance\Invoice\Service\Invoice
    public: true

  FreshAdvance\Invoice\Service\InvoiceServiceInterface:
    class: FreshAdvance\Invoice\Service\InvoiceService
    public: true
