services:
  _defaults:
    public: false
    autowire: true

  FreshAdvance\Invoice\InvoiceData\Service\InvoiceFileServiceInterface:
    class: FreshAdvance\Invoice\InvoiceData\Service\InvoiceFileService
    public: true

  FreshAdvance\Invoice\InvoiceData\Service\InvoiceDataServiceInterface:
    class: FreshAdvance\Invoice\InvoiceData\Service\InvoiceDataService
    public: true
