imports:
    - { resource: src/Repository/services.yaml }
    - { resource: src/Service/services.yaml }

services:
    _defaults:
        public: false
        autowire: true
        bind:
            OxidEsales\Eshop\Core\Config: '@=service("FreshAdvance\\Invoice\\Core\\Registry").getConfig()'

    FreshAdvance\Invoice\Core\Registry:
        class: OxidEsales\Eshop\Core\Registry
        public: true

    FreshAdvance\Invoice\Core\Utils:
        class: OxidEsales\Eshop\Core\Utils
        factory: [ 'OxidEsales\Eshop\Core\Registry', 'getUtils' ]
        public: true

    Mpdf\Mpdf:
        public: true

    FreshAdvance\Invoice\Service\:
        resource: 'src/Service/*'
        exclude: 'src/Service/{Context,RequestDataConverter,ModuleSettings,PdfGenerator}.php'
        public: true
