services:

  _defaults:
    public: false
    autowire: true

  OxidEsales\Eshop\Core\Registry:
    class: OxidEsales\Eshop\Core\Registry

  OxidEsales\Eshop\Core\Config:
    factory: [ '@OxidEsales\Eshop\Core\Registry', 'getConfig' ]

  OxidEsales\Eshop\Core\Request:
    factory: [ '@OxidEsales\Eshop\Core\Registry', 'getRequest' ]

  OxidEsales\Eshop\Core\Language:
    factory: [ '@OxidEsales\Eshop\Core\Registry', 'getLang' ]

  OxidEsales\Eshop\Core\Utils:
    factory: [ '@OxidEsales\Eshop\Core\Registry', 'getUtils' ]
    public: true

  Mpdf\Mpdf:
    public: true

  FreshAdvance\Invoice\Service\:
    resource: 'src/Service/*'
    public: true

  FreshAdvance\Invoice\Repository\:
    resource: 'src/Repository/*'