imports:
    - { resource: src/Document/services.yaml }
    - { resource: src/Repository/services.yaml }
    - { resource: src/Service/services.yaml }
    - { resource: src/Settings/services.yaml }
    - { resource: src/Language/Service/services.yaml }
    - { resource: src/Transput/services.yaml }

services:
    _defaults:
        public: false
        autowire: true

    FreshAdvance\Invoice\Core\Registry:
        class: OxidEsales\Eshop\Core\Registry
        public: true
