imports:
    - { resource: src/Email/services.yaml }
    - { resource: src/InvoiceData/services.yaml }
    - { resource: src/Pdf/services.yaml }
    - { resource: src/Language/Service/services.yaml }
    - { resource: src/Order/services.yaml }
    - { resource: src/Transput/services.yaml }

services:
    _defaults:
        public: false
        autowire: true

    FreshAdvance\Invoice\Core\Registry:
        class: OxidEsales\Eshop\Core\Registry
        public: true
