imports:
    - { resource: src/Repository/services.yaml }
    - { resource: src/Service/services.yaml }

services:
    _defaults:
        public: false
        autowire: true

    FreshAdvance\Invoice\Core\Registry:
        class: OxidEsales\Eshop\Core\Registry
        public: true

    FreshAdvance\Invoice\Transition\Core\UtilsInterface:
        class: OxidEsales\Eshop\Core\Utils
        factory: [ 'OxidEsales\Eshop\Core\Registry', 'getUtils' ]
        public: true
