services:
  _defaults:
    public: false
    autowire: true

  FreshAdvance\Invoice\Email\Service\InvoiceFilenameCalculatorInterface:
    class: FreshAdvance\Invoice\Email\Service\InvoiceFilenameCalculator
    public: true

  FreshAdvance\Invoice\Email\Service\InvoiceFilenameLengthFilter:
    decorates: FreshAdvance\Invoice\Email\Service\InvoiceFilenameCalculatorInterface
    arguments:
      $invoiceFilenameCalculator: '@.inner'

  FreshAdvance\Invoice\Email\Settings\EmailSettingsInterface:
    class: FreshAdvance\Invoice\Email\Settings\EmailSettings
    public: true
