services:
  _defaults:
    public: false
    autowire: true

  FreshAdvance\Invoice\Email\Settings\EmailSettingsInterface:
    class: FreshAdvance\Invoice\Email\Settings\EmailSettings
    public: true
