services:
  _defaults:
    public: false
    autowire: true
    bind:
      OxidEsales\Eshop\Core\Language: '@=service("FreshAdvance\\Invoice\\Core\\Registry").getLang()'

  FreshAdvance\Invoice\Language\Service\LanguageInterface:
    class: FreshAdvance\Invoice\Language\Service\LanguageProxy
    public: true
