imports:
  - { resource: Decoration/services.yaml }

services:
  _defaults:
    public: false
    autowire: true

  FreshAdvance\Invoice\Order\Repository\OrderRepositoryInterface:
    class: FreshAdvance\Invoice\Order\Repository\OrderRepository

  FreshAdvance\Invoice\Order\Service\OrderServiceInterface:
    class: FreshAdvance\Invoice\Order\Service\OrderService

  FreshAdvance\Invoice\Order\Settings\OrderSettingsInterface:
    class: FreshAdvance\Invoice\Order\Settings\OrderSettings
