services:
    _defaults:
        public: false
        autowire: true

    FreshAdvance\Invoice\Repository\:
        resource: './*'

    FreshAdvance\Invoice\Repository\InvoiceConfigurationRepositoryInterface:
        class: FreshAdvance\Invoice\Repository\InvoiceConfigurationRepository
