services:
  _defaults:
    public: false
    autowire: true
    bind:
      OxidEsales\Eshop\Core\Utils: '@=service("FreshAdvance\\Invoice\\Core\\Registry").getUtils()'

  FreshAdvance\Invoice\Transput\ResponseInterface:
    class: FreshAdvance\Invoice\Transput\ResponseProxy
    public: true
