imports:
  - { resource: InvoiceConfiguration/services.yaml }
  - { resource: Service/services.yaml }
  - { resource: Shop/services.yaml }
  - { resource: Transput/services.yaml }

services:
  _defaults:
    public: false
    autowire: true
