imports:
  - { resource: MpdfDocument/services.yaml }

services:
  _defaults:
    public: false
    autowire: true

  FreshAdvance\Invoice\Document\InvoiceGeneratorInterface:
    class: FreshAdvance\Invoice\Document\MpdfDocument\Builder
    public: true

  FreshAdvance\Invoice\Document\Service\DocumentRendererInterface:
    class: FreshAdvance\Invoice\Document\Service\DocumentRenderer
    public: true

  FreshAdvance\Invoice\Document\Service\FilenameCalculatorInterface:
    class: FreshAdvance\Invoice\Document\Service\FilenameCalculator
    public: true

  FreshAdvance\Invoice\Document\Service\FilenameLengthFilter:
    decorates: FreshAdvance\Invoice\Document\Service\FilenameCalculatorInterface
    arguments:
      $invoiceFilenameCalculator: '@.inner'

  FreshAdvance\Invoice\Document\Service\FilenameCharactersFilter:
    decorates: FreshAdvance\Invoice\Document\Service\FilenameCalculatorInterface
    arguments:
      $invoiceFilenameCalculator: '@.inner'

  FreshAdvance\Invoice\Document\Service\TemplateParametersServiceInterface:
    class: FreshAdvance\Invoice\Document\Service\TemplateParametersService

  FreshAdvance\Invoice\Document\Settings\DocumentLayoutSettingsInterface:
    class: FreshAdvance\Invoice\Document\Settings\DocumentLayoutSettings
