services:
  _defaults:
    public: false
    autowire: true

  FreshAdvance\Invoice\Geo\Factory\CountryModelFactoryInterface:
    class: FreshAdvance\Invoice\Geo\Factory\CountryModelFactory

  FreshAdvance\Invoice\Geo\Service\GeoServiceInterface:
    class: FreshAdvance\Invoice\Geo\Service\GeoService
