services:
  _defaults:
    public: false
    autowire: true

  FreshAdvance\Invoice\Document\MpdfDocument\MpdfFactory: ~

  Mpdf\Mpdf:
    factory: ['@FreshAdvance\Invoice\Document\MpdfDocument\MpdfFactory', 'create']
    public: true
