services:
  _defaults:
    public: false
    autowire: true
    bind:
      OxidEsales\Eshop\Core\Config: '@=service("FreshAdvance\\Invoice\\Core\\Registry").getConfig()'

  FreshAdvance\Invoice\InvoiceData\Settings\ContextInterface:
    class: FreshAdvance\Invoice\InvoiceData\Settings\Context

  FreshAdvance\Invoice\InvoiceData\Settings\FormatSettingsInterface:
    class: FreshAdvance\Invoice\InvoiceData\Settings\FormatSettings
    public: true

  FreshAdvance\Invoice\InvoiceData\Settings\ConfigInterface:
    class: FreshAdvance\Invoice\InvoiceData\Settings\ConfigProxy
