name: Trigger all configurations

on:
  workflow_dispatch:

jobs:
  shop70:
    if: always()
    uses: oxid-eSales/github-actions/.github/workflows/universal_workflow_light.yml@v4
    with:
      testplan: '~/defaults/7.0.x.yml,~/module-invoice.yml,~/_custom.yml'
      runs_on: '"ubuntu-latest"'
      defaults: 'v4'
      plan_folder: '.github/fresh-advance'
      custom_testplan_yaml: |
        global:
          title: '7.0.x-full'
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  shop71:
    if: always()
    uses: oxid-eSales/github-actions/.github/workflows/universal_workflow_light.yml@v4
    with:
      testplan: '~/defaults/7.1.x.yml,~/module-invoice.yml,~/_custom.yml'
      runs_on: '"ubuntu-latest"'
      defaults: 'v4'
      plan_folder: '.github/fresh-advance'
      custom_testplan_yaml: |
        global:
          title: '7.1.x-full'
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  shop72:
    if: always()
    uses: oxid-eSales/github-actions/.github/workflows/universal_workflow_light.yml@v4
    with:
      testplan: '~/defaults/7.2.x.yml,~/module-invoice.yml,~/_custom.yml'
      runs_on: '"ubuntu-latest"'
      defaults: 'v4'
      plan_folder: '.github/fresh-advance'
      custom_testplan_yaml: |
        global:
          title: '7.2.x-full'
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
