name: Trigger all configurations

on:
  workflow_dispatch:

jobs:
  shop71:
    if: always()
    uses: oxid-eSales/github-actions/.github/workflows/universal_workflow_light.yaml@v5
    with:
      testplan: '~/defaults/7.1.x.yaml,~/defaults/php8.2_mysql8.0_only.yaml,~/module-invoice.yaml,~/_custom.yaml'
      runs_on: '"ubuntu-latest"'
      defaults: 'v4'
      plan_folder: '.github/fresh-advance'
      custom_testplan_yaml: |
        global:
          title: '7.1.x-full'
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  shop72:
    if: always()
    uses: oxid-eSales/github-actions/.github/workflows/universal_workflow_light.yaml@v5
    with:
      testplan: '~/defaults/7.2.x.yaml,~/module-invoice.yaml,~/_custom.yaml'
      runs_on: '"ubuntu-latest"'
      defaults: 'v4'
      plan_folder: '.github/fresh-advance'
      custom_testplan_yaml: |
        global:
          title: '7.2.x-full'
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
