name: Auto trigger on push or pull requests
# Matrix workflow using re-usable github actions

on:
  pull_request: {}
  push: {}

jobs:
  shop70:
    uses: oxid-eSales/github-actions/.github/workflows/universal_workflow_light.yaml@v4
    with:
      testplan: '~/defaults/7.1.x.yaml,~/defaults/php8.2_mysql8.0_only.yaml,~/module-invoice.yaml,~/_custom.yaml'
      runs_on: '"ubuntu-latest"'
      defaults: 'v4'
      plan_folder: '.github/fresh-advance'
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
